### ISSUE TITLE
input for extract_genome_stats.py?

### ISSUE THREAD

**Issue by EmelineFavreau** [pbfrandsen/insect_genome_assemblies#1]
I am trying to understand the arguments for extract_genome_stats.py. 
The first is the csv created by convert2csv.py. But what is the accession_filename ?
Looking forward to trying this script!

**Comment by dagi34** [comment]
We are having the same issue as EmelineFavreau. Has this been solved please?
Thanks in advance. Regards

**Comment by pbfrandsen** [comment]
Thank you for reaching out. The accession_filename is a plain text file that includes the accession numbers of the assemblies that you want to extract, separated by line breaks. I will respond to the GitHub issue as well.
 
One other thing to note: the convert2csv.py script no longer works with the JSON output from NCBI datasets. Instead, I would use something like this: https://konklone.io/json/ then you can choose the columns that you would like to cut.
 
I hope that helps.
